### ISSUE TITLE
Login status or session should be cleared after closing browser or reinstallation 

### ISSUE THREAD

**Issue by wanglongfei88** [NeoNextClub/neoline#1]
Steps:
1. login NEOLine
2. close browser
3. re-open browser
4. check if the wallet still login

**Comment by hactrox** [comment]
All plugin related data will be cleared automatically after reinstallation so this is not the case.
The 'login required after closing browser' logic is not verbose enough so far, we will do more work on it.

**Comment by hactrox** [comment]
@wanglongfei88 Check out our latest release, it should now work as expected.
