### ISSUE TITLE
enhancements - add night mode & dapp logo

### ISSUE THREAD

**Issue by vincentgeneste** [NeoNextClub/neoline#10]
Hello, 

I would love to have a nightmode option, maybe defined in getwalletinfo extra?

Also, what defines the logo seen when connecting like here top left, how do I change it?

<img width="387" alt="Screen Shot 2019-05-05 at 20 55 34" src="https://user-images.githubusercontent.com/25534589/57206506-0cec8b00-6f7b-11e9-96fb-8c5150bd2fe0.png">

**Comment by hactrox** [comment]
@vincentgeneste 
We are preparing the Light/Dark mode now, but as its priority is not very high, this feature will not be released very soon.
As for the logo, NEOLine will try to read it from your website(favicon). We've patched an updated on it, check our new release to see if it works.
![image](https://user-images.githubusercontent.com/8434402/58156324-6dccd080-7ca8-11e9-8231-e8bdc660fcdf.png)

**Comment by vincentgeneste** [comment]
Tested, everything works perfectly!
