### ISSUE TITLE
Restoring wallet from json

### ISSUE THREAD

**Issue by taykeshi** [NeoNextClub/neoline#14]
Can't restore my wallet. It never offered me a private key when I singed up, but I did download the json (nep2) file. 
I accidentally deleted neolin from my browser, and since I don't have my private key (since it was never given to me), I try to use the nep2 file restore function.

Problem: 
whenever I try to open it, nothing happens. I select the file, but as soon as I do, neoline closes and nothing happens. 
Can't drag and drop either because as soon as I click somewhere else, neoline closes again...

What can I do?

**Comment by hkhv** [comment]
1.
![image](https://user-images.githubusercontent.com/28698877/60249408-61671380-98f7-11e9-8d5a-fb11254714ce.png)

2.
![image](https://user-images.githubusercontent.com/28698877/60249417-66c45e00-98f7-11e9-94c4-e6af9b2ca0c9.png)

3.
![image](https://user-images.githubusercontent.com/28698877/60249440-704dc600-98f7-11e9-897f-212ce1a43e19.png)

4.
![image](https://user-images.githubusercontent.com/28698877/60249460-780d6a80-98f7-11e9-9ffb-43dfc9ff7b98.png)

**Comment by taykeshi** [comment]
Yeah, I can't do that. I select the file and then neoline closes.

**Comment by hactrox** [comment]
Hi, we cannot reproduce this issue, if it still bother you, please tell us the following info:
1. What operation system are you using?
2. Which version of chrome are you using?
3. Which version of NEOLine are you using?
4. Could you generate/export a new NEP2 file and test it again? If the same thing, could you paste the file content here or mail us?
