### ISSUE TITLE
signMessage does not follow the standard

### ISSUE THREAD

**Issue by corollari** [NeoNextClub/neoline#17]
signMessage, which uses the function `sign` defined [here](https://github.com/NeoNextClub/neoline/blob/master/extension/common/utils.ts) does not follow the standard, which says the following:

Signs a provided messaged with an account selected by user. A randomized salt prefix is added to the input string before it is signed, and it is encased in a non-executable transaction before signed. This ensures allow compatibility with Ledger devices.

**Comment by hactrox** [comment]
Confirmed, the standard [has changed](https://github.com/neo-project/proposals/pull/69/commits/7a8e1cd3e7733100fc29eafb0c89cabd28d4f58a#diff-0d131719c9cb9204e0c60d353c22748eR1222)
Thanks for your reminding, it will be updated soon.

**Comment by raisezhang** [comment]
+1 

NeoLine's signMessage and verifyMessage validation failed，without adding randomized salt.

https://github.com/NeoNextClub/neoline/blob/17a5b27f31fca2b5444487fe3af9a758a71b6c8a/extension/neoline/index.ts#L257

**Comment by hactrox** [comment]
Updated, signMessage has followed the latest standard.

**Comment by raisezhang** [comment]
It works.   Thanks @hactrox
