### ISSUE TITLE
Receiving transaction id but it never actually sends transaction

### ISSUE THREAD

**Issue by amack2u** [NeoNextClub/neoline#18]
Hello...I was just doing some test transactions on neo TestNet with our dapp...and i seem to be having issues with NeoLine browser extension. When i send a transaction i get neoline popup to approve...I type my password it says wait and then the popup does not disappear. I have to close it manually and in my browser console i get send transaction success with an id but a blank rpc node url...and when i check the block explorer that transaction does not exist. Is that a known issue with the browser extension and testnet?

here is the payload passed into the send function:

amount: "1"
asset: "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b"
broadcastOverride: false
fee: "0.0011"
fromAddress: "Aa3RHMgKjY7E64fU2Ma7a6owpSFxsvjGRS"
network: "TestNet"
remark: "NEOLine"
toAddress: "APMnoZwSw9CpmPk14risaYgTbmZB32fKzJ"

using latest version 0.12.1
I have tried using the assetID hash and symbol...
I am able to send with browser extension directly but not from dapp...any suggestions?

**Comment by hactrox** [comment]
Hi!
We have tested transfers on TestNet and it worked as expected.
Maybe this is a network issue, can you ping `testnet.api.neoline.cn` and tell us the result?

**Comment by amack2u** [comment]
I dont think that is the issue... i can ping and send directly using the browser extension...here is a stripped down version with the issue. use on test net

Please try here: https://cmxeg.csb.app/

here is source codepen editor:
https://codesandbox.io/embed/vue-quasar-latest-working-cmxeg

**Comment by hactrox** [comment]
@amack2u Hello, can you please test it again to see if it works now?
