### ISSUE TITLE
deploy() does not work

### ISSUE THREAD

**Issue by corollari** [NeoNextClub/neoline#19]
## Steps to reproduce:
Execute:
```js
neoline.deploy({
    "name": "appname",
    "version": "v1.0",
    "author": "author",
    "email": "email",
    "description": "appdescription",
    "needsStorage": true,
    "dynamicInvoke": true,
    "isPayable": false,
    "parameterList": "",
    "returnType": "ff00",
    "code": "00c56b0548656c6c6f09576173686a6f726c64617c68164e656f2e53746f726167652e476574436f6e74657874680f4e656f2e53746f726167652e507574616c7566",
    "networkFee": "0"
})
```
with NeoLine's network set to TestNet.

The code parameter is a compiled version of the following script:
```
using Neo.SmartContract.Framework.Services.Neo;

namespace Neo.SmartContract
{
    public class HelloWorld : Framework.SmartContract
    {
        public static void Main()
        {
            // writes value "World" on storage key "Hello"
            // implicitly calls Storage.Put(Storage.CurrentContext, "Hello", "World")
            Storage.Put("Hello", "Washjorld");
        }
    }
}
```

## Expected results
The script is deployed on testnet.

## Obtained results
The call returns saying that it has been successful but the script is not deployed and the amount of gas in my wallet stays the same.

**Comment by hactrox** [comment]
Thanks for your report and sorry for the late response, this bug is reproduced and has been fixed.
By the way, according to [https://github.com/MorganDream/neo-unified-dapi](url), starting from 1.1.0, all the event types has been updated.
