### ISSUE TITLE
Import Wallet by Nep6 wallet file

### ISSUE THREAD

**Issue by wanglongfei88** [NeoNextClub/neoline#20]
There is a mistake about wallet file. 

Based on neo proposal, wallet file proposal is nep6. So we normally call nep6 wallet file. Please help to correct the mistake.

![image](https://user-images.githubusercontent.com/34025001/71959449-bdf3a580-322d-11ea-92de-d1a8a94f52fc.png)

**Comment by hactrox** [comment]
Thanks for your report, we'll handle it.

**Comment by hactrox** [comment]
Sorry for the late response(I forget it for some reason).
I'll close this issue since it had been fixed already.
