### ISSUE TITLE
Provide Claim Gas function 

### ISSUE THREAD

**Issue by wanglongfei88** [NeoNextClub/neoline#3]
If user owns NEO in their wallet, GAS will be generated for that user. So in NEOLine, user should be able to see how much GAS is claimable, and also be able to claim GAS.

**Comment by hactrox** [comment]
@wanglongfei88 Thanks for your advice. We've implemented this feature, will release it soon.

**Comment by hactrox** [comment]
'Claim GAS' is now provided, please refer to our latest release.
