### ISSUE TITLE
Add asset symbol to transfer

### ISSUE THREAD

**Issue by vincentgeneste** [NeoNextClub/neoline#6]
Hello,

When initiating a transfer, it only shows the amount, but not the symbol transferred, could you add that too ?

See screenshot below where we don't know what's being sent.

<img width="373" alt="Screen Shot 2019-05-05 at 21 08 43" src="https://user-images.githubusercontent.com/25534589/57206368-11647400-6f7a-11e9-8b5c-a7bac5f91089.png">

**Comment by hactrox** [comment]
@vincentgeneste Good advice :). We will add it in the next release

**Comment by vincentgeneste** [comment]
Working now, thanks :)
