### ISSUE TITLE
getWalletInfo extra missing currency

### ISSUE THREAD

**Issue by vincentgeneste** [NeoNextClub/neoline#7]
Hello,

getWalletInfo extra is returning nothing, while it should at least returns the currency (USD / CNY).

**Comment by hactrox** [comment]
We have upgraded the dAPI standard, and the relevant dapi is called 'getProvider' now, which will return these fields. Click [here](https://neoline.cn/dapi/#getProvider) for detail.

**Comment by vincentgeneste** [comment]
Works as intended thx.
