### ISSUE TITLE
add an event to check if neoline is defined/ready

### ISSUE THREAD

**Issue by vincentgeneste** [NeoNextClub/neoline#8]
Hello,

In the case when someone handle multiple dapi, we need to have a global event to listen when neoline is ready, as opposed to having it defined with var neoline = new NEOLine.Init()

What I would like is to be able to use something like this if possible:

            window.addEventListener('neoline.READY', function(ready) {

            })

**Comment by hactrox** [comment]
dAPI updated, here is the relevant documentation:
https://neoline.cn/dapi/#addEventListener
https://neoline.cn/dapi/#READY
Hope it meets your needs.

**Comment by vincentgeneste** [comment]
Works perfectly now! :)
