### ISSUE TITLE
disconnect() function

### ISSUE THREAD

**Issue by vincentgeneste** [NeoNextClub/neoline#9]
I would like to have a disconnect() function available on NEOLine dApi, so that I can trigger a new wallet connection if the user wants to change the wallet.

Basically something which triggers a disconnect event and then allows me to listen to that event.

**Comment by hactrox** [comment]
We have updated our dAPI standard and this event was added: https://neoline.cn/dapi/#DISCONNECTED

**Comment by vincentgeneste** [comment]
Hello! It is not what I wanted unfortunately. That's still an interesting event to have, but I would love to have is a way to TRIGGER a disconnect from the app side. like a disconnect() function.

**Comment by hactrox** [comment]
It's not like 'connect and keep the connection(alive)', but more like 'contact the wallet and do one thing every time', so after the wallet instance initialized you can call all the functions immediately rather than have to call the 'connect()', 'disconnect()' or sth first.
